// export interface ItemsTYPE {
//     barcode: string | null;
//     description: string;
//     itemCode: string;
//     qty: string;
//     itemSequence: string;
//     orderType: string;
//     address1: string | null;
//     address2: string | null;
// }

// Generated by https://quicktype.io

export interface ItemsTYPE {
    general: General;
    orders: Order[];
}

export interface General {
    ordertype: string;
    checked: number;
    orderId: string;
}

export interface Order {
    barcode: null | string;
    description: string;
    itemCode: string;
    qty: number;
    itemSequence: string;
    orderType: string;
    address1: null | string;
    address2: null | string;
}
